### ISSUE TITLE
self hosted runner CI token scope

### ISSUE THREAD

**Issue by jschwe** [servo/ci-runners#11]
I was just checking the readme and saw that the tokens for the CI runners require

> Repository permissions > Administration > Access: Read and write

which gives permissions for

>  Repository creation, deletion, settings, teams, and collaborators. 

I was wondering what these permissions are required for and if there is some way to avoid them, since giving a token for CI runners the permissions to delete repositories seems a bit overkill.

**Comment by delan** [comment]
This was a mistake on my part. I combined the permissions for both prod (org runners) and testing (repo runners), but actually, only repo runners need repo admin permissions. See our current prod token:

![image](https://github.com/user-attachments/assets/af7dd7c1-8869-4877-b718-a2455dd90baf)

I’ll fix the docs now.
