### ISSUE TITLE
Publish new base images with `rustc 1.82` and `uv`

### ISSUE THREAD

**Issue by mukilan** [servo/ci-runners#12]
https://github.com/servo/servo/pull/34270 upgrades the version of rustc we use for building servo. Additionally, once https://github.com/servo/servo/pull/34632 is merged, we will start using `uv` for bootstrapping the Python installation for `mach`.

 It would be good to have new images with the same [version of rust toolchain](https://github.com/servo/ci-runners/blob/d7173b3e219f344588f958390ef658e07d3cbc8e/ubuntu2204/init.sh#L14) and `uv` to avoid installing the tools on each build CI build.

**Comment by jschwe** [comment]
I would also like to bump rustc again to v1.82 to get access to the new raw pointers feature - if its just a few clippy lints, perhaps we do a quick follow bump to 1.82, and directly update the runner updates to 1.82

**Comment by mukilan** [comment]
We probably need to install `ccache` as well to support building mozjs from source - see https://github.com/servo/servo/issues/34603#issuecomment-2544621524 and https://github.com/servo/servo/blame/a37a9f68b810e0e7d2a2d4cce4b9e5706288c434/.github/workflows/windows.yml#L102

**Comment by delan** [comment]
Working on this now :)

**Comment by delan** [comment]
Deployed!

**Comment by delan** [comment]
I forgot to actually bump the Rust version in init.sh and init.ps1, but that’s ok, because when we prebuild Servo we pull in the correct version anyway. Failing to bump the Rust version just bloats the images a bit.
